plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.163'
    id 'io.github.goooler.shadow' version '8.1.7'
}

version = "${mod_version}+neoforge.${minecraft_version}"
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

runs {
    configureEach {
        workingDirectory project.file('run')
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
        modSource project.sourceSets.main
    }

    client {
        systemProperty 'forge.enabledGameTestNamespaces', mod_id
    }

    server {
        systemProperty 'forge.enabledGameTestNamespaces', mod_id
        programArgument '--nogui'
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    mavenCentral()
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"

    implementation 'org.mariuszgromada.math:MathParser.org-mXparser:5.2.1'
    implementation('net.sf.jopt-simple:jopt-simple:5.0.4') { version { strictly '5.0.4' } }
}

shadowJar {
    dependencies {
        include(dependency('org.mariuszgromada.math:MathParser.org-mXparser:5.2.1'))
    }
    archiveClassifier.set('')
    relocate 'org.mariuszgromada.math.mxparser', 'net.jsa2025.calcmod.mxparser'
}

tasks.named('jar', Jar).configure {
    archiveClassifier.set('slim')
    manifest {
        attributes([
            'Specification-Title'     : mod_id,
            'Specification-Vendor'    : mod_authors,
            'Specification-Version'   : '1',
            'Implementation-Title'    : project.name,
            'Implementation-Version'  : project.jar.archiveVersion,
            'Implementation-Vendor'   : mod_authors,
            'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
        minecraft_version   : minecraft_version,
        minecraft_version_range: minecraft_version_range,
        neo_version         : neo_version,
        neo_version_range   : neo_version_range,
        loader_version_range: loader_version_range,
        mod_id              : mod_id,
        mod_name            : mod_name,
        mod_license         : mod_license,
        mod_version         : mod_version,
        mod_authors         : mod_authors,
        mod_description     : mod_description,
    ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/neoforge.mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
