# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://fabricmc.net/develop

minecraft_version=26.2
yarn_mappings=1.21.10+build.1
loader_version=0.16.10

# Fabric API


# Mod Properties
	ver = 1.5.2
	maven_group = com.jsa2025
	archives_base_name = CalcMod

# Dependencies
fabric_version=0.119.6+1.21.5

