# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://fabricmc.net/develop

minecraft_version=26.1
loader_version=0.18.4
loom_version=1.15-SNAPSHOT
yarn_mappings=26.1+build.1

fabric_version=0.144.1+26.1






# Mod Properties
	mod_version = 1.5.0
	maven_group = com.jsa2025
	archives_base_name = calcmod


