# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# NeoForge
neo_version=21.1.219
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version_range=[21.1,)
loader_version_range=[4,)

# Mappings
mapping_channel=official
mapping_version=1.21.1

# Mod
mod_id=calcmod
mod_name=CalcMod
mod_license=MIT
mod_version=1.4.2
mod_group_id=net.jsa2025.calcmod
mod_authors=jsa2025
mod_description=Calculator mod in chat with minecraft related functions.
