name: Auto Updater
on:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: js802025/calcmod-updater@v1
        with:
          github-token: ${{ github.token }}
  
